### ISSUE TITLE
 link not working

### ISSUE THREAD

**Issue by tommasoo0** [VKappaKV/Zero-To-Hero-blockchain-Algorand#1]
The third link in "fundamentals" section isnt working.

"[Light primer for blockchain and Solidity Smart Contracts](https://www.blockchainworkbench.com/)"

**Comment by VKappaKV** [comment]
Thank you for opening the issue Tommaso, I'll see if I can find a replacement for that content, seems like the page was taken down. Otherwise I'll just remove that
